// Devices /////////
#define PRINTER 1
#define CONVEYOR 2
#define LOADER 3
#define WEBSERVER 9
////////////////////

// Status Codes
#define	STT_METHOD 800
#define STT_JOB_SUBMITTED 801
#define STT_JOB_STARTED 802
#define STT_JOB_DONE 803
#define STT_PRINTING 810
#define STT_MOVING_TO_PRINTER 820
#define STT_MOVING_TO_DELIVERY 821
#define STT_LOADING 830
#define STT_UNLOADING 831
#define	STT_BARCODE 832

// Error Codes
#define ERR_METHOD  900
#define ERR_BLUETOOTH_COMMUNICATION  901
#define ERR_JOB_NOT_STARTED  902
#define ERR_NO_BRICKS 910
#define ERR_BRICK_NOT_PICKED 911
#define ERR_BRICK_NOT_PLUGGED 912
#define ERR_BRICK_MISPLUGGED 913
#define ERR_NO_PLATES 930

// Commands
#define CONVEYOR_JOB_START 201
#define CONVEYOR_JOB_DONE 202
#define CONVEYOR_JOB_DISCARD 203
#define CONVEYOR_PLATE_LOADED 204
#define CONVEYOR_MOVE 210
#define PRINTER_PRINT 101
#define LOADER_LOAD_PLATE 301
